### ISSUE TITLE
1v1/1v2 Booster combo

### ISSUE THREAD

**Issue by mGm-Lizard** [lf94/3SPN_Enhanced_A#26]
Add option that enables booster combo for the team with only one player on it. If new player joins the 1v2, booster needs to auto disable.

**Comment by mGm-Lizard** [comment]
I will have to tag this when I get home. For some reason, there isn't an option to do so via mobile phone.

**Comment by mGm-Lizard** [comment]
#enhancement

**Comment by lf94** [comment]
To me this is such a specific special scenario in the game that it's kind of uncalled for. It also has to keep a bunch of options in mind.

**Comment by lf94** [comment]
Welp looks like its wanted :V

**Comment by lf94** [comment]
Tiny adjustment: combos always on if there is one person on a team.

**Comment by mGm-Lizard** [comment]
LoL. I knew it was wanted. Did you make it optional?

**Comment by lf94** [comment]
All done. Needs testing.
