### ISSUE TITLE
try to fix frozen player right click return to frozen body

### ISSUE THREAD

**Issue by mGm-Lizard** [lf94/3SPN_Enhanced_A#27]
Sometimes works correctly.

**Comment by lf94** [comment]
Need more description

**Comment by mGm-Lizard** [comment]
Have you noticed this happening @lf94

**Comment by lf94** [comment]
Too hard to reproduce. Think it's happening because the camera or original player pawn de-spawns. Unless we find the exact cause I'm keeping this closed.
