### ISSUE TITLE
Shield Gun alt fire

### ISSUE THREAD

**Issue by mGm-Lizard** [lf94/3SPN_Enhanced_A#29]
Lireal informed us of this on 4/19/16. basically, if you are frozen while using the shield gun (the shield part of it), then when you thaw, your maximum shield gun charges become a random number between 0 and 100. So, sometimes you'll thaw and you'll have 0 shield. Sometimes 12, or sometimes 72. And when it discharges and recharges, it will only recharge to that number, never higher.

**Comment by lf94** [comment]
Fixed.
