### ISSUE TITLE
Add concurrent versioning to the GameName default property.

### ISSUE THREAD

**Issue by mGm-Lizard** [lf94/3SPN_Enhanced_A#34]
I think adding concurrent versioning to each GameName is a good idea. If there are two different versions of 3SPN on a server, in web admin, you will see two Freon, Team Arena Master v3, Arena Master, and IG Freon. There's no way to tell which version of 3spn each goes with.

**Comment by mGm-Lizard** [comment]
All that's left is to do is a pull request to the master branch.

**Comment by lf94** [comment]
If it's resolved then close it...No need to keep it open
