### ISSUE TITLE
create 3SPN new default loading screens and server ini file option for admin to set their own loading screens

### ISSUE THREAD

**Issue by lf94** [lf94/3SPN_Enhanced_A#6]

**Comment by mGm-Lizard** [comment]
`static function bool ReplaceLoadingScreen(PlayerController PCL, string MapName)
{
    local Object O;
    local UT2K4ServerLoading LoadingScreenObj;
    local Texture LoadingScreenTex;
    
    foreach PCL.AllObjects(class'Object', O)
        if (LoadingScreenObj == None && O.Class == class'UT2K4ServerLoading')
        {
            LoadingScreenObj = UT2K4ServerLoading(O);
            break;
        }
        
    LoadingScreenTex = Texture(DynamicLoadObject("3SPNv3223TR.LS.loading" $ (Rand(7) + 1), class'Texture', true));
    
    if (LoadingScreenObj != None && LoadingScreenTex != None)
    {
        DrawOpImage(LoadingScreenObj.Operations[0]).Image = LoadingScreenTex;
        return true;
    }
    
    return false;
}`
